### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by fySam** [blepfx/dist#1]
Hello, how do i put destruqtor in fl? i moved the vst3 file in the steinberg folder but it doesnt get scanned by fl.

**Comment by Quant1um** [comment]
Hi, for FL Studio the installation process is as follows:
- Copy the vst3 file into `C:/Program Files/Common Files/VST3/` (assuming you're on windows)
- Open FL Studio and go to Options > General > Manage Plugins
- Make sure `C:/Program Files/Common Files/VST3/` is in the `Plugin search paths` list (it should be there by default)
- Click `Find installed plugins`
