### ISSUE TITLE
Issue with destruqtor window dimensions

### ISSUE THREAD

**Issue by hamsterfactor** [blepfx/dist#2]
destruqtor 0.1.0 is restricted to the lower left corner of the window in Reason 13 on Mac Studio M1 with Sonoma 14.7.

It's functional, but looks odd. See my screenshot.
<img width="504" alt="Screenshot 2024-10-13 at 12 15 10" src="https://github.com/user-attachments/assets/6c01276b-a8ce-4f12-8553-98c6b2d7db6b">

**Comment by Quant1um** [comment]
Hi ^^ Thanks for the report

Please update destruqtor to the latest version (v1.0.2), it should be fixed
If the issue persists, let me know
